---
title: "CSCD429 Lab2"
author: "Joseph Riddle"
date: "October 9, 2018"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.a
```{r}
x <- 1:20
x
```
## 1.b
```{r}
x <- c(1:20, 19:1)
x
```
## 1.c
```{r}
tmp <- 2 * 1:3
tmp
```

## 1.d
```{r}
tmp <- rep(2 * 1:3, 10)
tmp
```
or
```{r}
tmp <- rep(2 * 1:3, each = 10)
tmp
```

## 2.a
```{r}
v <- c(1,5,-2,1,2,-1,3,6,-3)
A <- matrix(v, nrow = 3, ncol = 3)
A
```
or
```{r}
A <- c(1,5,-2,1,2,-1,3,6,-3)
dim(A) <- c(3,3)
A
```
or
```{r}
x <- c(1,5,-2)
y <- c(1,2,-1)
z <- c(3,6,-3)
A <- cbind(x,y,z)
A
```

## 2.b
```{r}
A * A * A
```

## 2.c
```{r}
A[,3] <- A[,1] + A[,2]
A
```

## 2.d
```{r}
B <- t(A)
B
```

## 2.e
```{r}
A + B
```

## 2.f
```{r}
A - B
```

## 2.g
```{r}
I <- diag(3)
I
```

## 3
```{r}
x <- matrix(c(1, 2, 3, 4, 5, 2, 1, 2, 3, 4, 3, 2, 1, 2, 3, 4, 3, 2, 1, 2, 5, 4, 3, 2, 1), 5, 5)
x
b <- matrix(c(7, -1, -3, 5, 17), 5, 1)
b
solve(x, b)
```

